version: '2'
services:
  lychee-nginx:
    build: ./nginx
    container_name: lychee-nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./lychee/php-fpm:/var/run/php-fpm
      - ./lychee/src:/var/www/html 
    #NOTE : TLS key's path for HTTPS
    # - <host ssl_certificate key's path> : <nginx.conf ssl_certificate key's path>
    # - <host ssl_certificate_key key's path> : <nginx.conf  ssl_certificate_key key's path>
    networks:
      - app_net
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - lychee
    command: ["nginx", "-g", "daemon off;"]
  lychee-mariadb:
    build: ./mariadb
    container_name: lychee-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: lychee
      MYSQL_USER: lychee
      MYSQL_PASSWORD: lychee
    volumes_from:
      - lychee-mariadb-storage
    volumes:
      - /var/lib/mysql
      - ./mariadb/config/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_net
    hostname: lychee-mariadb
    expose:
      - "3306"
    command: ["mysqld"]
  lychee-mariadb-storage:
    build: ./storage/mariadb-storage
    container_name: mariadb-storage
    volumes:
     - ./storage/mariadb-storage/data:/var/lib/mysql
  lychee:
    build: ./lychee
    container_name: lychee
    environment:
      MYSQL_USER: lychee
      MYSQL_PASSWORD: lychee
    volumes:
      - ./lychee/php-fpm:/var/run/php-fpm
    networks:
      - app_net
    hostname: lychee
    expose:
      - "80"
      - "443"
networks:
  app_net:
    driver: bridge